changesDir: .changes
unreleasedDir: unreleased
headerPath: header.tpl.md
versionHeaderPath: ""
changelogPath: CHANGELOG.md
versionExt: md
versionFormat: '## {{.Version}} - [{{.Time.Format "January 02, 2006"}}](https://github.com/OpsLevel/terraform-provider-opslevel/compare/{{.PreviousVersion}}...{{.Version}})'
kindFormat: '### {{.Kind}}'
changeFormat: '- {{.Body}}'
kinds:
  - label: Bugfix
  - label: Feature
  - label: Security
  - label: Refactor
  - label: Deprecated
  - label: Removed
  - label: Docs
  - label: Dependency
newlines:
  afterChangelogHeader: 1
  afterKind: 1
  afterChangelogVersion: 1
  beforeKind: 1
  endOfVersion: 1
