# https://taskfile.dev/

version: '3'

vars:
  # 'VERSION_DYNAMIC' needs to run in this scope before 'task build' begins
  VERSION_DYNAMIC:
    sh: echo "$(date +%s).0.0"

includes:
  go:
    taskfile: "./opslevel/Taskfile.yml"
  terraform:
    taskfile: "./workspace/Taskfile.yml"
    dir: ./workspace
    aliases: [tf]

tasks:

  ready-plan:
    desc: Run build and init followed by terraform plan in workspace/
    cmds:
      - task: build
      - task: tf:init
      - task: tf:plan

  ready-apply:
    desc: Run build and init followed by terraform apply in workspace/
    cmds:
      - task: build
      - task: tf:init
      - task: tf:force-apply

  ready-destroy:
    desc: Run build and init followed by terraform destroy in workspace/
    cmds:
      - task: build
      - task: tf:init
      - task: tf:force-destroy

  build:
    desc: Build local opslevel terraform provider
    platforms: [darwin]
    vars:
      BINARY: terraform-provider-opslevel_{{.VERSION_DYNAMIC}}
      LOCATION: "${HOME}/.terraform.d/plugins/registry.terraform.io/opslevel/opslevel/{{.VERSION_DYNAMIC}}/{{OS}}_{{ARCH}}"
    cmds:
      - go build -o {{.BINARY}} || exit 1
      - chmod +x {{.BINARY}}
      - mkdir -p {{.LOCATION}}
      - mv {{.BINARY}} {{.LOCATION}}/{{.BINARY}}

  install-changie:
    desc: Install changie
    aliases: [get-changie]
    cmds:
      - cmd: echo "Installing changie..."
        silent: true
      - go install github.com/miniscruff/changie@latest
      - cmd: echo -e "\nSuccess! 'changie' installed."
        silent: true

  lint:
    desc: Check formatting and linting
    cmds:
      - task: go:lint
      - task: terraform:lint

  lintfix:
    desc: Fix formatting and linting
    cmds:
      - task: go:lintfix
      - task: terraform:lintfix

  setup:
    desc: Setup env and tools
    cmds:
      - task: install-changie
      - task: go:setup
      - task: build
      - task: terraform:init

  test:
    desc: Run tests
    env:
      TF_ACC: true
    cmds:
      - task: go:test
