# https://taskfile.dev/

version: '3'

includes:
  go:
    taskfile: "./opslevel/Taskfile.yml"
  terraform:
    taskfile: "./workspace/Taskfile.yml"
    aliases: [tf]

tasks:

  install-changie:
    desc: Install changie
    cmds:
      - cmd: echo "Installing changie..."
        silent: true
      - go install github.com/miniscruff/changie@latest
      - cmd: echo -e "\nSuccess! 'changie' installed."
        silent: true

  lint:
    desc: Check formatting and linting
    cmds:
      - task: go:lint
      - task: terraform:lint

  lintfix:
    desc: Fix formatting and linting
    cmds:
      - task: go:lintfix
      - task: terraform:lintfix

  setup:
    desc: Setup env and tools
    cmds:
      - task: go:setup
      - task: terraform:setup
      - task: install-changie

  test:
    desc: Run tests
    dir: "opslevel"
    env:
      TF_ACC: true
    cmds:
      - task: go:test
