# https://taskfile.dev/

version: '3'

vars:
  # 'VERSION_DYNAMIC' needs to run in this scope before 'task build' begins
  VERSION_DYNAMIC:
    sh: echo "$(git describe --tags --abbrev=0 | tr -d 'v')$(date +%s)"

includes:
  go:
    taskfile: "./opslevel/Taskfile.yml"
  terraform:
    taskfile: "./workspace/Taskfile.yml"
    dir: ./workspace
    aliases: [tf]

tasks:

  build:
    desc: Build local opslevel terraform provider
    platforms: [darwin]
    vars:
      BINARY: terraform-provider-opslevel_{{.VERSION_DYNAMIC}}
      BINARY_PATH_BEFORE_VERSION: "${HOME}/.terraform.d/plugins/registry.terraform.io/opslevel/opslevel"
      OS_ARCH:
        sh: echo $(go env GOOS)_$(go env GOARCH)
      VERSION_FROM_BINARY:
        sh: echo {{.BINARY}} | cut -d '_' -f 2
    cmds:
      - go build -o {{.BINARY}} || exit 1
      - chmod +x {{.BINARY}}
      - mkdir -p {{.BINARY_PATH_BEFORE_VERSION}}/{{.VERSION_FROM_BINARY}}/{{.OS_ARCH}}
      - mv {{.BINARY}} {{.BINARY_PATH_BEFORE_VERSION}}/{{.VERSION_FROM_BINARY}}/{{.OS_ARCH}}
      - cmd: echo "Built terraform provider at:"
        silent: true
      - cmd: echo "{{.ROOT_DIR}}/{{.BINARY_PATH_BEFORE_VERSION}}/{{.VERSION_FROM_BINARY}}/{{.OS_ARCH}}/{{.BINARY}}"
        silent: true

  install-changie:
    desc: Install changie
    aliases: [get-changie]
    cmds:
      - cmd: echo "Installing changie..."
        silent: true
      - go install github.com/miniscruff/changie@latest
      - cmd: echo -e "\nSuccess! 'changie' installed."
        silent: true

  lint:
    desc: Check formatting and linting
    cmds:
      - task: go:lint
      - task: terraform:lint

  lintfix:
    desc: Fix formatting and linting
    cmds:
      - task: go:lintfix
      - task: terraform:lintfix

  setup:
    desc: Setup env and tools
    cmds:
      - task: install-changie
      - task: go:setup
      - task: build
      - task: terraform:init

  test:
    desc: Run tests
    env:
      TF_ACC: true
    cmds:
      - task: go:test
