# https://taskfile.dev/

version: '3'
env:
  OPSLEVEL_GO_PKG: "github.com/opslevel/opslevel-go/v2024"

tasks:

  fix:
    desc: Fix formatting and linting of go code
    deps: [install-gofumpt, install-golangci-lint]
    cmds:
      - task: update-opslevel-go
      - gofumpt -w .
      - go mod tidy
      - golangci-lint run --fix
      - nilaway -fix -test=false ./...

  has-latest-opslevel-go:
    desc: Check if latest release of opslevel-go in go.mod
    dir: "{{.ROOT_DIR}}"
    silent: true
    vars:
      GO_WORK: "go.work"
      TMP_GO_WORK: "tmp_go.work"
      LATEST_OPSLEVEL_GO_VERSION:
        sh: go list -u -m -versions github.com/opslevel/opslevel-go/v2024 | awk '{print $NF}'
    cmds:
      - if [[ -f {{.GO_WORK}} ]]; then mv {{.GO_WORK}} {{.TMP_GO_WORK}}; fi
      - defer: if [[ -f {{.TMP_GO_WORK}} ]]; then mv {{.TMP_GO_WORK}} {{.GO_WORK}}; fi
      - |-
        if [[ {{.LATEST_OPSLEVEL_GO_VERSION}} == $(go list -m --json '{{.OPSLEVEL_GO_PKG}}' | jq -r '.Version') ]]; then
          echo "Using latest version of opslevel-go - {{.LATEST_OPSLEVEL_GO_VERSION}}";
        else
          echo "WARNING: current version of opslevel-go is behind '{{.LATEST_OPSLEVEL_GO_VERSION}}'"
          echo "Run 'task fix' to get latest version"
          exit 1
        fi

  lint:
    desc: Check formatting and linting of go code
    deps: [install-gofumpt, install-golangci-lint]
    cmds:
      - test -z "$(gofumpt -d -e . | tee /dev/stderr)"
      - golangci-lint run
      - nilaway -test=false ./...

  setup:
    desc: Setup go linter, formatter, and opslevel-go submodule
    cmds:
      - task: install-gofumpt
      - task: install-golangci-lint
      - task: install-nilaway
      - task: setup-opslevel-go

  setup-opslevel-go:
    desc: Setup go workspace to import opslevel-go
    internal: true
    cmds:
      - git submodule update --init --remote
      - rm go.work go.work.sum || true
      - go work init
      - go work use . submodules/opslevel-go
      - echo "Workspace ready!"

  test:
    desc: Run go tests
    cmds:
      - go test -race -coverprofile=coverage.out -covermode=atomic -v ./... {{ .CLI_ARGS }}
      - grep -v "/enum.go" coverage.out > coverage.txt
    silent: true

  update-opslevel-go:
    desc: Update opslevel-go version to latest release
    dir: "{{.ROOT_DIR}}"
    cmds:
      - go get -u "{{.OPSLEVEL_GO_PKG}}"

  ########################################
  # internal (not directly called) tasks #
  ########################################

  install-go-tool:
    internal: true
    silent: true
    vars:
      IS_TOOL_INSTALLED:
        sh: which {{.GO_TOOL}} > /dev/null || echo "1"
    cmds:
      - test -z "{{.IS_TOOL_INSTALLED}}" || echo "Installing {{.GO_TOOL}}..."
      - test -z "{{.IS_TOOL_INSTALLED}}" || go install {{.GO_TOOL_PATH}}
      - test -n $(go env GOBIN) || go env -w GOBIN=$(go env GOPATH)/bin
    requires:
      vars: [GO_TOOL, GO_TOOL_PATH]

  install-gofumpt:
    desc: go install "gofumpt" and set GOBIN if not set
    internal: true
    silent: true
    cmds:
      - task: install-go-tool
        vars: { GO_TOOL: "gofumpt", GO_TOOL_PATH: "mvdan.cc/gofumpt@latest" }

  install-golangci-lint:
    desc: go install "golangci-lint" and set GOBIN if not set
    internal: true
    silent: true
    cmds:
      - task: install-go-tool
        vars: { GO_TOOL: "golangci-lint", GO_TOOL_PATH: "github.com/golangci/golangci-lint/cmd/golangci-lint@latest" }

  install-nilaway:
    desc: go install "nilaway"
    internal: true
    cmds:
      - task: install-go-tool
        vars: { GO_TOOL: "nilaway", GO_TOOL_PATH: "go.uber.org/nilaway/cmd/nilaway@latest" }
