name: Dependabot Labels

on:
  # Runs when PR is labeled by Dependabot or via the Github UI
  pull_request:
    types:
      - labeled

jobs:
  pr-labeled:
    if: github.event.label.name == 'dependencies'
    runs-on: ubuntu-latest
    steps:
      - name: Trigger workflow
        run: echo "Triggering workflow_run to generate Changie logs"

