name: Webhook

on:
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: 'true'
      - name: Fetch all tags
        run: git fetch --force --tags
      - id: next_version
        uses: zwaldowski/semver-release-action@v3
        with:
          dry_run: true
          bump: ${{ … }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Show the next version
        run: |
          echo ${{ steps.next_version.outputs.version }}
