name: Webhook

on:
  repository_dispatch:
    types:
      - webhook

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: 'true'
      - name: Fetch all tags
        run: git fetch --force --tags
      - name: Run
        env:
          PAYLOAD: ${{ toJSON(github.event.client_payload) }}
        run: |-
          ls -al
          echo $PAYLOAD
