name: Webhook

on:
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: 'true'
      - name: Fetch all tags
        run: git fetch --force --tags
      - name: Get Next Version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          branch: main
      - name: Show the next version
        run: |
          echo ${{ steps.semver.outputs.next }}
