name: Security
permissions:
  contents: read

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 13 * * 1"  # 8am CT on Mondays

jobs:
  call-grype:
    uses: opslevel/actions/.github/workflows/grype.yml@main
    with:
      alias: terraform-provider-opslevel
    secrets: inherit
