name: Integration Tests

on:
  workflow_dispatch:
    inputs:
      tf_version:
        description: "Terraform version to use for integration testing"
        type: choice
        default: "~1.10.0"
        options:
          - "~1.6.0"
          - "~1.7.0"
          - "~1.8.0"
          - "~1.9.0"
          - "~1.10.0"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ github.event.inputs.tf_version }}
          terraform_wrapper: false
      - name: Tests using only this repo
        run: task test-integration
        env:
          OPSLEVEL_API_TOKEN: ${{ secrets.OPSLEVEL_PAT_API_TOKEN }}
      - name: Setup OpsLevel CLI
        uses: opslevel/actions/setup-cli@v1
      - name: Tests using Terraform OpsLevel Modules repo
        run: task test-unreleased
        env:
          OPSLEVEL_API_TOKEN: ${{ secrets.OPSLEVEL_PAT_API_TOKEN }}
