name: Integration Tests
permissions:
  contents: read

on:
  workflow_dispatch:
    inputs:
      tf_version:
        description: "Terraform version to use for integration testing"
        type: choice
        default: "~1.10.0"
        options:
          - "~1.6.0"
          - "~1.7.0"
          - "~1.8.0"
          - "~1.9.0"
          - "~1.10.0"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: 'true'
      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v6
        with:
          go-version-file: go.mod
      - name: Install Task
        uses: arduino/setup-task@c0bc642852239c2689f73f4ea6459c29405f3c52 # v3.0.0
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1
        with:
          terraform_version: ${{ github.event.inputs.tf_version }}
          terraform_wrapper: false
      - name: Tests using only this repo
        run: task test-integration
        env:
          OPSLEVEL_API_TOKEN: ${{ secrets.OPSLEVEL_PAT_API_TOKEN }}
#      - name: Setup OpsLevel CLI
#        uses: opslevel/actions/setup-cli@v1
#      - name: Tests using Terraform OpsLevel Modules repo
#        run: task test-unreleased
#        env:
#          OPSLEVEL_API_TOKEN: ${{ secrets.OPSLEVEL_PAT_API_TOKEN }}
